/// Flutter icons Harika
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Harika
///      fonts:
///       - asset: fonts/Harika.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Harika {
  Harika._();

  static const _kFontFam = 'Harika';
  static const String? _kFontPkg = null;

  static const IconData selcuk = IconData(0xeba4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
